spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mar?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  header: Authorization
  secret: 123456
  expiration: 604800
  tokenHead: "Bearer"
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "session/1"
debug: true
logging:
  level: debug
